---
- name: Assert platform is supported
  tags: ssl-certificates
  assert:
    that:
      - ansible_os_family in ['Debian', 'RedHat']

- include_vars: "{{ ansible_os_family }}.yml"
  tags: ssl-certificates


- name: Update apt package cache
  tags: ssl-certificates
  when: ansible_os_family == 'Debian'
  apt:
    update_cache=yes
    cache_valid_time=3600

- name: Install required packages
  tags: ssl-certificates
  with_items: ssl_certificates_package_list
  action: "{{ ansible_pkg_mgr }} state=installed name={{ item }}"


- name: Create self-signed certificates
  tags: ssl-certificates
  with_items: ssl_certificates_create
  command:
    openssl req
      -new
      -nodes
      -x509
      -subj {{ item.subj|default("/C=DE/ST=Hamburg/L=Hamburg/O=IT/CN={{ansible_fqdn}}") }}
      -days {{ item.days|default(3650) }}
      -keyout {{ item.key }}
      -out {{ item.certificate }}
      -extensions v3_ca
    creates={{ item.certificate }}

- name: Copy existing certificates
  tags: ssl-certificates
  with_items: ssl_certificates_copy
  copy:
    src={{ item.src }}
    dest={{ item.dest }}
