---
- name: Assert platform is supported
  tags: ssl-certificate
  assert:
    that:
      - ansible_os_family in ['Debian', 'RedHat']

- name: Update apt package cache
  tags: ssl-certificate
  when: ansible_os_family == 'Debian'
  apt:
    update_cache=yes
    cache_valid_time=3600

- name: Intall openssl
  tags: ssl-certificate
  action: "{{ ansible_pkg_mgr }} state=installed name=openssl"

- name: Create self-signed certificates
  tags: ssl-certificate
  with_items: ssl_certificates_create
  command:
    openssl req
    -new
    -nodes
    -x509
    -subj {{ item.subj|default( "/C=DE/ST=Hamburg/L=Hamburg/O=IT/CN={{ansible_fqdn}}")}}
    -days {{ item.days|default(3650) }}
    -keyout {{ item.key }}
    -out {{ item.certificate }}
    -extensions v3_ca creates={{ item.certificate }}

- name: Copy certificates
  tags: ssl-certificate
  with_items: ssl_certificates_copy
  copy:
    dest={{ item.dest }}
    src={{ item.src }}
